<?php echo $this->doctype(); ?>
<html lang="pl">
    <head>
        <?php $this->headMeta()->setCharset('UTF-8'); ?>
        <?php echo $this->headTitle('Consulting-Man developed by gRRinch')->setSeparator(' | ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('description', 'Quick Consultation application made by gRRinch. We&#039;ll see how it goes ;-)')
                ->appendName('robots', 'noindex, nofollow')
                ->appendHttpEquiv('pragma', 'no-cache')
                ->appendHttpEquiv('Cache-Control', 'no-cache')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pl-PL')
                ->setAutoEscape(true);
        echo "\n";
        echo $this->headLink()
                ->prependStylesheet('/style.css');
        echo "\n";
        if(!stristr($_SERVER['REQUEST_URI'], 'admin')) {
            echo $this->headScript()
                ->prependFile('/ajax.js')
                ->prependFile('http://js.pusher.com/2.1/pusher.min.js');
        }
        echo $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js')
                ->prependFile('/js/jquery.min.js');
        echo "\n";
        ?>

    </head>
    <body>
        <div id="main_container">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
